apiVersion: apps/v1 
kind: Deployment
metadata:
  name: flower-app-deployment
spec: #define the deployement behaviout
  replicas : 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec: #defines the pod deployement
      containers:
      - name: cart-app
        image: muralisocial123/flower-app:1.0
        resources:
          limits:
            memory: "250Mi"
            cpu: "100m"
          requests:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 3015
